apiVersion: batch/v1
kind: CronJob
metadata:
  name: slash-points
  namespace: monitoring
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: slash-points
              image: ghcr.io/validat0rs/cron:v0.0.1
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 1m
                  memory: 100Mi
              env:
                - name: DD_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: datadog-agent
                      key: api-key
              command: ["/bin/sh"]
              args:
                - "+x"
                - "/scripts/slash_points.sh"
                - "thor18jmgnzck5mjtxpq7e7z6mqkt3ynvjermfrxj82"
                - "thorchain01"
              volumeMounts:
                - name: slash-points
                  mountPath: /scripts
          volumes:
            - name: slash-points
              configMap:
                name: slash-points
                defaultMode: 0744
          restartPolicy: Never
      backoffLimit: 0
